import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],

  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Sundarban Courier Service (Pvt.) Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main>
          <Header /> {children} <Footer />
        </main>
      </body>
    </html>
  );
}
